name: CI

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        architecture: x64
    - name: Install poetry
      run: sudo pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Run tests
      run: poetry run nosetests --with-doctest tests
      env:
        DISCOURSE_API_KEY: _

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
          python-version: '3.13'
    - uses: pre-commit/action@v3.0.1

  build:
    needs: tests
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: flipdot/forumbot:latest
