name: CI

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install pipenv
      run: sudo pip install pipenv
    - name: Install dependencies
      run: pipenv sync
    - name: Install style checker
      run: pip install flake8
    - name: Run style check
      run: flake8 .
    - name: Run tests
      run: pipenv run nosetests --with-doctest tests
      env:
        DISCOURSE_API_KEY: _

  build:
    needs: tests
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: flipdot/forumbot:latest