name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - name: Install pipenv
      run: sudo pip install pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Install stylechecker
      run: pip install flake8
    - name: Run stylecheck
      run: flake8 .
    - name: Install nosetests
      run: pip install nose
    - name: Run tests
      run: nosetests --with-doctest tests